webapp/models.py
from flask_sqlalchemy import SQLAlchemy
from flask_login import AnonymousUserMixin
from .extensions import bcrypt


db = SQLAlchemy()

roles = db.Table('role_users',
                 db.Column('user_id', db.Integer, db.ForeignKey('user.id')),
                 db.Column('role_id', db.Integer, db.ForeignKey('role.id'))
                 )


class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(255))
    password = db.Column(db.String(255))
    posts = db.relationship(
        'Post',
        backref='user',
        lazy='dynamic'
    )

    roles = db.relationship('Role',
                            secondary=roles,
                            backref=db.backref('users', lazy='dynamic')
                            )

    def __init__(self, username):
        self.username = username

    def __repr__(self):
        return "<User '{}'>".format(self.username)

    def set_password(self, password):
        self.password = bcrypt.generate_password_hash(password)

    def check_password(self, password):
        return bcrypt.check_password_hash(self.password, password)

    def is_authenticated(self):
        if isinstance(self, AnonymousUserMixin):
            return False
        else:
            return True

    def is_active(self):
        return True

    def is_anonymous(self):
        if isinstance(self, AnonymousUserMixin):
            return True
        else:
            return False

    def get_id(self):
        return str(self.id)


tags = db.Table('post_tags',
                db.Column('post_id', db.Integer, db.ForeignKey('post.id')),
                db.Column('tag_id', db.Integer, db.ForeignKey('tag.id')),
                )


class Post(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))
    body = db.Column(db.Text)
    publish_time = db.Column(db.DateTime)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    comments = db.relationship('Comment',
                               backref='post',
                               lazy='dynamic',
                               )
    tags = db.relationship(
        'Tag',
        secondary=tags,
        backref=db.backref('posts', lazy='dynamic')
    )

    def __init__(self, title):
        self.title = title

    def __repr__(self):
        return '<Post {}>'.format(self.title)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255))

    def __init__(self, title):
        self.title = title

    def __repr__(self):
        return '<Tag: {}>'.format(self.title)


class Comment(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(255))
    text = db.Column(db.Text)
    date = db.Column(db.DateTime)
    post_id = db.Column(db.Integer, db.ForeignKey('post.id'))

    def __repr__(self):
        return '<Comment: {}>'.format(self.text[:15])


class Role(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(80), unique=True)
    description = db.Column(db.String(255))

    def __init__(self, name):
        self.name = name

    def __repr__(self):
        return '<Role: {}>'.format(self.name)

webapp/forms.py
from flask_wtf import Form
from wtforms import StringField, TextAreaField, PasswordField, BooleanField
from wtforms.validators import DataRequired, Length, EqualTo, URL
from .models import User


'''表单'''


class LoginForm(Form):
    username = StringField('Username',
                           [DataRequired(), Length(max=20)]
                           )
    password = PasswordField('Password', [DataRequired()])

    remember = BooleanField('记住我')

    def validate(self):
        check_validate = super(LoginForm, self).validate()
        if not check_validate:
            return False

        user = User.query.filter_by(username=self.username.data).first()
        if not user:
            self.username.errors.append(
                '用户名密码错误'
            )
            return False

        if not user.check_password(self.password.data):
            self.username.errors.append(
                '用户名密码错误'
            )
            return False
        return True
        

class RegisterForm(Form):
    username = StringField('Username', [DataRequired(), Length(max=20)])
    password = PasswordField('Password', [DataRequired(), Length(min=8)])
    check_password = PasswordField('Confirm Password', [DataRequired(), EqualTo('password')])
    
    def validate(self):
        check_validate = super(RegisterForm, self).validate()
        if not check_validate:
            return False

        user = User.query.filter_by(username=self.username.data).first()
        if user:
            self.username.errors.append(
                '用户名已存在'
            )
            return False
        return True


class PostForm(Form):
    title = StringField('Title', [DataRequired(), Length(max=100)])
    text = TextAreaField('Content', [DataRequired()])


class CommentForm(Form):
    name = StringField('Name', validators=[DataRequired(), Length(max=20)])
    text = TextAreaField(u'Comment', validators=[DataRequired()])

webapp/__init__.py
from flask import Flask, redirect, url_for
from flask_principal import identity_loaded, UserNeed, RoleNeed
from flask_login import current_user

from .models import db
from .controllers.blog import blog_blueprint
from .controllers.main import main_blueprint
from .extensions import bcrypt, login_manager, principals


def create_app(object_name):
    app = Flask(__name__)
    app.config.from_object(object_name)

    db.init_app(app)
    bcrypt.init_app(app)
    login_manager.init_app(app)
    principals.init_app(app)

    @identity_loaded.connect_via(app)
    def on_identity_loaded(sender, identity):
        identity.user = current_user

        if hasattr(current_user, 'id'):
            identity.provides.add(UserNeed(current_user.id))

        if hasattr(current_user, 'roles'):
            for role in current_user.roles:
                identity.provides.add(RoleNeed(role.name))


    @app.route('/')
    def index():
        return redirect(url_for('blog.home'))

    app.register_blueprint(blog_blueprint)
    app.register_blueprint(main_blueprint)

    return app

webapp/controllers/blog.py
import datetime
from flask import  render_template, Blueprint, redirect, url_for, abort
from sqlalchemy import func
from flask_login import login_required, current_user
from flask_principal import Permission, UserNeed

from webapp.models import Post, User, db, Tag, Comment, tags
from webapp.forms import CommentForm, PostForm
from webapp.extensions import poster_permission, admin_permission


blog_blueprint = Blueprint(
    'blog',
    __name__,
    template_folder='../templates/blog',
    url_prefix="/blog"
)


'''视图函数'''


def sidebar_data():
    recent = Post.query.order_by(
        Post.publish_time.desc()
    ).limit(5).all()

    toptags = db.session.query(
        Tag, func.count(tags.c.post_id).label('total')
    ).join(
        tags
    ).group_by(Tag).order_by('total DESC').limit(5).all()

    return recent, toptags


@blog_blueprint.route('/')
@blog_blueprint.route('/<int:page>')
def home(page=1):
    posts = Post.query.order_by(
        Post.publish_time.desc()
    ).paginate(page, 5)
    recent, toptags = sidebar_data()

    return render_template('index.html', posts=posts, recent=recent, toptags=toptags)


@blog_blueprint.route('/post/<int:post_id>', methods=('GET', 'POST'))
def post(post_id):
    form = CommentForm()
    if form.validate_on_submit():
        new_comment = Comment()
        new_comment.name = form.name.data
        new_comment.text = form.text.data
        new_comment.post_id = post_id
        new_comment.date = datetime.datetime.now()
        db.session.add(new_comment)
        db.session.commit()
    post = Post.query.get_or_404(post_id)
    user = User.query.filter_by(id=post.user_id).first_or_404()
    comments = post.comments.order_by(Comment.date.desc()).all()
    tags = post.tags
    recent, toptags = sidebar_data()

    return render_template('post.html',
                           post=post,
                           user=user,
                           comments=comments,
                           tags=tags,
                           recent=recent,
                           toptags=toptags,
                           form=form
                           )


@blog_blueprint.route('/tag/<string:tag_name>/')
def tag(tag_name):
    tag = Tag.query.filter_by(title=tag_name).first_or_404()
    posts = tag.posts.order_by(Post.publish_time.desc()).all()
    recent, toptags = sidebar_data()

    return render_template('tag.html', tag=tag, posts=posts, recent=recent, toptags=toptags)


@blog_blueprint.route('/user/<string:user_name>')
def user(user_name):
    user = User.query.filter_by(username=user_name).first_or_404()
    posts = user.posts.order_by(Post.publish_time.desc())
    recent, toptags = sidebar_data()

    return render_template('user.html', user=user, posts=posts, recent=recent, toptags=toptags)


@blog_blueprint.route('/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()

    if form.validate_on_submit():
        new_post = Post(form.title.data)
        new_post.body = form.text.data
        new_post.publish_time = datetime.datetime.now()
        new_post.user = current_user
        db.session.add(new_post)
        db.session.commit()

    return render_template('new.html', form=form)


@blog_blueprint.route('/edit/<int:id>', methods=['GET', 'POST'])
@login_required
@poster_permission.require(http_exception=403)
def edit_post(id):
    post = Post.query.get_or_404(id)
    permission = Permission(UserNeed(post.user.id))

    if permission.can() or admin_permission.can():
        form = PostForm()

        if form.validate_on_submit():
            post.title = form.title.data
            post.body = form.text.data
            post.publish_time = datetime.datetime.now()

            db.session.add(post)
            db.session.commit()

            return redirect(url_for('.post', post_id=post.id))

        form.text.data = post.body
        return render_template('edit.html', form=form, post=post)
    abort(403)

webapp/controllers/main.py
from flask import Blueprint, redirect, url_for,render_template, flash, current_app
from flask_login import login_user, logout_user
from flask_principal import Identity, AnonymousIdentity, identity_changed
from ..forms import LoginForm, RegisterForm
from ..models import User
from webapp import db


main_blueprint = Blueprint(
    'main',
    __name__,
    template_folder='../templates/main'
)


@main_blueprint.route('/')
def index():
    return redirect(url_for('blog.home'))


@main_blueprint.route('/login', methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        login_user(user, remember=form.remember.data)

        identity_changed.send(
            current_app._get_current_object(),
            identity=Identity(user.id)
        )
        flash("登录成功", category="success")
        return redirect(url_for('blog.home'))
    return render_template('login.html', form=form)


@main_blueprint.route('/logout', methods=['GET', 'POST'])
def logout():
    logout_user()
    identity_changed.send(
        current_app._get_current_object(),
        identity=AnonymousIdentity()
    )
    flash("退出登录成功", category="success")
    return redirect(url_for('.login'))


@main_blueprint.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        new_user = User(form.username.data)
        new_user.set_password(form.password.data)

        db.session.add(new_user)
        db.session.commit()

        flash("注册成功,请登录", category="success")
        return redirect(url_for('.login'))
    return render_template('register.html', form=form)

webapp/templates/blog/base.html
{% macro render_pagination(pagination, endpoint, page) %}
     <nav>
        <ul class="pagination">
            <li>
                {% if pagination.has_prev %}
                <a href="{{ url_for(endpoint, page=pagination.prev().page) }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
                {% else %}
                <a href="" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
                {% endif %}
            </li>
            {% for page in pagination.iter_pages() %}
              {% if page %}
                {% if page != pagination.page %}
                <li>
                    <a href="{{ url_for(endpoint, page=page) }}">
                        {{ page }}
                    </a>
                </li>
                {% else %}
                <li>
                    <a href="">{{ page }}</a>
                </li>
                {% endif %}
              {% else %}
                <li><a>...</a></li>
              {% endif %}
            {% endfor %}
            <li>
                {% if pagination.has_next %}
                <a href="{{ url_for(endpoint, page=pagination.next().page) }}" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
                {% else %}
                <a href="" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
                {% endif %}
            </li>
        </ul>
     </nav>
{% endmacro %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Blog{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='css/bootstrap.css') }}">
</head>
<body>
    <div class="container">
        <div class="jumbotron">
            <h1><a href="{{ url_for('blog.home') }}">MyBlog</a></h1>
            <p>Welcome!!!!</p>
        </div>
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }} alert-dismissable" role="alert">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    {{ message }}
                    </div>

                {% endfor %}

            {% endif %}
        {% endwith %}
        {% block body %}
        {% endblock%}
    </div>
    <script src="http://libs.baidu.com/jquery/1.11.2/jquery.min.js"></script>
    <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
</body>
</html>

webapp/templates/blog/edit.html
{% extends "base.html" %}
{% block title %}编辑文章{% endblock %}
{% block body %}
<div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h1 class="text-center">编辑文章</h1>
            <form method="POST" action="{{ url_for('.edit_post', id=post.id) }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.title.label }}
                    {% if form.title.errors %}
                        {% for e in form.title.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.title(class_='form-control', value=post.title) }}
                </div>
                <div class="form-group">
                    {{ form.text.label }}
                    {% if form.text.errors %}
                        {% for e in form.text.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.text(id="editor", class_='form-control') }}
                </div>
                <input class="btn btn-primary" type="submit" value="完成">
            </form>
            <hr>
            <a href="{{ url_for('.post', post_id=post.id) }}">
                <button type="button" class="btn btn-primary">返回</button>
            </a>
        </div>
        <div class="col-md-4"></div>
    </div>
{% endblock %}
{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
<script>
CKEDITOR.replace('editor');
</script>    
{% endblock %}

webapp/templates/blog/index.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="row">
    <div class="col-lg-9">
        {% for post in posts.items %}
        <div class="row">
            <div class="col-lg-12">
                <h1>{{ post.title }}</h1>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                {{ post.body | truncate(100) | safe }}
                <a href="{{ url_for('blog.post', post_id=post.id)}}">Read More</a>
            </div>
        </div>
        {% endfor %}
     {{ render_pagination(posts, 'blog.home', page)}}
    </div>
    <div class="col-lg-3">
        <div class="row">
            <h5>热门文章</h5>
            <ul>
                {% for post in recent %}
                <li><a href="{{ url_for('blog.post', post_id=post.id) }}">
                    {{ post.title }}
             </a></li>
                {% endfor %}
         </ul>
    </div>
        <div class="row">
            <h5>热门标签</h5>
            <ul>
                {% for tag in toptags %}
                <li><a href="{{ url_for('blog.tag', tag_name=tag[0].title) }}">
                    {{ tag[0].title }}
                </a> </li>
                {% endfor %}
            </ul>
        </div>
    </div>

</div>
{% endblock %}

webapp/templates/blog/new.html
{% extends "base.html" %}
{% block title %}新文章{% endblock %}
{% block body %}
<div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <h1 class="text-center">新文章</h1>
            <form method="POST" action="{{ url_for('.new_post') }}">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.title.label }}
                    {% if form.title.errors %}
                        {% for e in form.title.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.title(class_='form-control') }}
                </div>
                <div class="form-group">
                    {{ form.text.label }}
                    {% if form.text.errors %}
                        {% for e in form.text.errors %}
                            <p class="help-block">{{ e }}</p>
                        {% endfor %}
                    {% endif %}
                    {{ form.text(id="editor", class_='form-control') }}
                </div>
                <input class="btn btn-primary" type="submit" value="完成" href="{{ url_for('.home') }}">
            </form>
            <hr>
            <a href="{{ url_for('.home') }}">
                <button type="button" class="btn btn-primary">返回</button>
            </a>
        </div>
        <div class="col-md-4"></div>
    </div>
{% endblock %}
{% block js %}
<script src="//cdn.ckeditor.com/4.4.7/standard/ckeditor.js"></script>
<script>
CKEDITOR.replace('editor');
</script>
{% endblock %}

webapp/templates/blog/post.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="row">
    <div class="col-lg-9">
        <div class="row">
            <div class="col-lg-12">
                <h1>{{ post.title }}</h1>
                <h5>
                    作者：
                    <a href="{{ url_for('blog.user', user_name=user.username)}}">
                    <span>{{ user.username }}</span>
                    </a>
                </h5>
                <h5>
                    标签：
                    {% for tag in tags %}
                    <a href="{{ url_for('blog.tag', tag_name=tag.title) }}">
                        <span>{{ tag.title }}</span>
                    </a>
                    {% endfor %}
                </h5>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <span>
                    {{ post.body | safe }}
                </span>
            </div>
        </div>
    </div>
    <div class="col-lg-6">
        <h3>发表评论</h3>
        <form method="post" action="{{ url_for('blog.post', post_id=post.id) }}">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.name.label }}
                {% if form.name.error %}
                    {% for e in form.name.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                {% endif %}
                {{ form.name(class_='form-control') }}
            </div>
            <div class="form-group">
                {{ form.text.label }}
                {% if form.text.error %}
                    {% for e in form.text.errors %}
                    <p class="help-block">{{ e }}</p>
                    {% endfor %}
                {% endif %}
                {{ form.text(class_='form.control') }}
            </div>
            <input class="btn btn-primary" type="submit" value="发表">
        </form>
    </div>
    <div class="col-lg-3">
        <div class="row">
            <h5>热门文章</h5>
            <ul>
                {% for post in recent %}
                <li><a href="{{ url_for('blog.post', post_id=post.id) }}">
                    {{ post.title }}
             </a></li>
                {% endfor %}
         </ul>
    </div>
        <div class="row">
            <h5>热门标签</h5>
            <ul>
                {% for tag in toptags %}
                <li><a href="{{ url_for('blog.tag', tag_name=tag[0].title) }}">
                    {{ tag[0].title }}
                </a> </li>
                {% endfor %}
            </ul>
        </div>
    </div>

</div>
{% endblock %}

webapp/templates/blog/tag.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="row">
    <div class="col-lg-9">
        <div class="row">
            <div class="col-lg-12">
                <h1>{{ tag.title }}</h1>
            </div>
        </div>
        {% for post in posts %}
        <div class="row">
            <div class="col-lg-12">
                <a href="{{ url_for('blog.post', post_id=post.id)}}">
                    <h3>{{ post.title | safe }}</h3>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-lg-3">
        <div class="row">
            <h5>热门文章</h5>
            <ul>
                {% for post in recent %}
                <li><a href="{{ url_for('blog.post', post_id=post.id) }}">
                    {{ post.title }}
             </a></li>
                {% endfor %}
         </ul>
    </div>
        <div class="row">
            <h5>热门标签</h5>
            <ul>
                {% for tag in toptags %}
                <li><a href="{{ url_for('blog.tag', tag_name=tag[0].title) }}">
                    {{ tag[0].title }}
                </a> </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}

webapp/templates/blog/user.html
{% extends "base.html" %}
{% block title %}Home{% endblock %}
{% block body %}
<div class="row">
    <div class="col-lg-9">
        <div class="row">
            <div class="col-lg-12">
                <h1>{{ user.username }}</h1>
            </div>
        </div>
        {% for post in posts %}
        <div class="row">
            <div class="col-lg-12">
                <a href="{{ url_for('blog.post', post_id=post.id)}}">
                    <h3>{{ post.title | safe }}</h3>
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
    <div class="col-lg-3">
        <div class="row">
            <h5>热门文章</h5>
            <ul>
                {% for post in recent %}
                <li><a href="{{ url_for('blog.post', post_id=post.id) }}">
                    {{ post.title }}
             </a></li>
                {% endfor %}
         </ul>
    </div>
        <div class="row">
            <h5>热门标签</h5>
            <ul>
                {% for tag in toptags %}
                <li><a href="{{ url_for('blog.tag', tag_name=tag[0].title) }}">
                    {{ tag[0].title }}
                </a> </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</div>
{% endblock %}